/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface File {
  id: Generated<string>;
  filename: string;
  mimetype: string;
  size: Int8;
  url: string;
}

export interface Todo {
  id: Generated<string>;
  completed: Generated<boolean>;
  deletedAt: Timestamp | null;
  isActive: Generated<boolean>;
  task: string;
  createdAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
}

export interface Tokens {
  expiresAt: Timestamp | null;
  key: string;
  value: string;
}

export interface Users {
  id: Generated<string>;
  address: string | null;
  avatar: string | null;
  dob: Timestamp | null;
  email: string;
  firstName: string;
  gender: string | null;
  isActive: Generated<boolean>;
  isDeleted: Generated<boolean>;
  lastName: string;
  name: string;
  password: string;
  phone: string;
  createdAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  file: File;
  todo: Todo;
  tokens: Tokens;
  users: Users;
}
